{% set version = "2021.2.0" %}

package:
  name: pymor
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pymor/pymor-{{ version }}.tar.gz
  sha256: 0d71af7cfc8cf84896603b8138c76bc7cd2dd1909b714ee02cf0b78eaf778443

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv
  skip: true  # [py<37]

requirements:

  host:
    - python
    - pip
    - numpy
    - packaging
    - pytest-runner
    - wheel

  run:
    - python
    - typer
    - pythreejs
    - ipywidgets
    - ipython >=3.0
    - ipyparallel
    - matplotlib-base
    - pyopengl
    - diskcache
    - pyqt ==5.12.3
    # these should really be a dependcy of pyqt, but isn't
    - xorg-libxi  # [linux]
    - xorg-libxrender  # [linux]
    - pillow
    - {{ pin_compatible('numpy') }}
    - scipy >=0.13.3
    - docopt
    - Qt.py
    - packaging
    - mpi4py  # [not win]
    - jupyter
    - pyvista

test:
  requires:
    - pytest >=4.6
    - hypothesis
    - packaging
    - mpich  # [not win]

  imports:
    - pymor
    - pymordemos

about:
  home: https://pymor.org
  license: BSD-2-Clause
  license_file: LICENSE.txt
  summary: pyMOR is a software library for building model order reduction applications with the Python programming language. Implemented algorithms include reduced basis methods for parametric linear and non-linear problems, as well as system-theoretic methods such as balanced truncation or IRKA. All algorithms in pyMOR
    are formulated in terms of abstract interfaces for seamless integration with external PDE solver packages. Moreover, pure Python implementations of finite element and finite volume discretizations using the NumPy/SciPy scientific computing stack are provided for getting started quickly.

extra:
  recipe-maintainers:
    - renefritze
