{% set name = "pymor" %}
{% set version = "2025.1.1" %}
{% set python_min = "3.9" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 916894f612ee016979148592a9507523b36a7531688e2e4409e09a196c770549

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv
  entry_points:
    - pymor-demo = pymor.scripts.pymor_demo:run
    - pymor-vis = pymor.scripts.pymor_vis:run

requirements:

  host:
    - python {{ python_min }}
    - pip
    - numpy
    - packaging
    - pytest-runner
    - wheel
    - hatchling

  run:
    - python >={{ python_min }}
    - diskcache
    - matplotlib-base
    - numpy >=1.20.3,!=1.25.0
    - packaging
    - pillow
    - pygments
    - qtpy >=2.3.1
    - scipy >=1.8,!=1.15.0,!=1.15.1,!=1.15.2
    - threadpoolctl
    - typer

test:
  requires:
    - python {{ python_min }}
    - hypothesis[numpy,pytest] ==6.56.3
    - packaging
    - pytest >=7.2.1
    - pytest-cov
    - pytest-datadir
    - pytest-notebook

  imports:
    - pymor
    - pymordemos

about:
  home: https://pymor.org
  license: BSD-2-Clause
  license_file: LICENSE.txt
  summary: >
    pyMOR is a software library for building model order reduction applications
    with the Python programming language. All algorithms in pyMOR are
    formulated in terms of abstract interfaces, allowing generic
    implementations to work with different backends, from NumPy/SciPy to
    external partial differential equation solver packages.

extra:
  recipe-maintainers:
    - HenKlei
    - lbalicki
    - pmli
    - sdrave
